using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_StatBlock = M_StatBlock;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Attribute")]
public partial class M_Attribute : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5759024008653899620UL,12933057861602087844UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public BansheeGz.BGDatabase.BGEntity f_definition
	{
		get => _f_definition[Entity.Index];
		set => _f_definition[Entity.Index] = value;
	}
	public System.Single f_baseValue
	{
		get => _f_baseValue[Entity.Index];
		set => _f_baseValue[Entity.Index] = value;
	}
	public System.String f_type
	{
		get => _f_type[Entity.Index];
		set => _f_type[Entity.Index] = value;
	}
	public System.Single f_value
	{
		get => _f_value[Entity.Index];
		set => _f_value[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4912605891296361063UL, 16153373923074003903UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_definition;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_definition => _ufle12jhs77_f_definition ?? (_ufle12jhs77_f_definition = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5622187512205097438UL, 11020210589490312617UL), () => _ufle12jhs77_f_definition = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_baseValue;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_baseValue => _ufle12jhs77_f_baseValue ?? (_ufle12jhs77_f_baseValue = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5183687754903258558UL, 7299324960166985386UL), () => _ufle12jhs77_f_baseValue = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_type;
	public static BansheeGz.BGDatabase.BGFieldString _f_type => _ufle12jhs77_f_type ?? (_ufle12jhs77_f_type = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5054515395608882712UL, 17669332049266674836UL), () => _ufle12jhs77_f_type = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_value;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_value => _ufle12jhs77_f_value ?? (_ufle12jhs77_f_value = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5576080448177196863UL, 5316653968039754174UL), () => _ufle12jhs77_f_value = null));
	public List<BGEntity> RelatedStatBlockListUsingstatsRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_StatBlock._f_stats, Entity.Id);
}
