using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Attribute = M_Attribute;
using Alias_rifegrt_Vital = M_Vital;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_AttributeDefinition")]
public partial class M_AttributeDefinition : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5022464699769892086UL,14568507806228298116UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name => _f_name[Entity.Index];
	public System.Single f_startingValue => _f_startingValue[Entity.Index];
	public System.String f_relationship => _f_relationship[Entity.Index];
	public System.String f_type => _f_type[Entity.Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5554287556442847067UL, 502824818088638614UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_startingValue;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_startingValue => _ufle12jhs77_f_startingValue ?? (_ufle12jhs77_f_startingValue = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5361260929856468790UL, 18125555978075553435UL), () => _ufle12jhs77_f_startingValue = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_relationship;
	public static BansheeGz.BGDatabase.BGFieldString _f_relationship => _ufle12jhs77_f_relationship ?? (_ufle12jhs77_f_relationship = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5096499396903204262UL, 16618904729035510659UL), () => _ufle12jhs77_f_relationship = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_type;
	public static BansheeGz.BGDatabase.BGFieldString _f_type => _ufle12jhs77_f_type ?? (_ufle12jhs77_f_type = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5705046718452188874UL, 1427258789523882419UL), () => _ufle12jhs77_f_type = null));
	public List<BGEntity> RelatedAttributeListUsingdefinitionRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_Attribute._f_definition, Entity.Id);
	public List<BGEntity> RelatedVitalListUsingdefinitionRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_Vital._f_definition, Entity.Id);
}
