using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Player = M_Player;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Camera")]
public partial class M_Camera : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5339483879621403676UL,6492147764873338759UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public System.Single f_yRotation
	{
		get => _f_yRotation[Entity.Index];
		set => _f_yRotation[Entity.Index] = value;
	}
	public System.Int32 f_zoomStep
	{
		get => _f_zoomStep[Entity.Index];
		set => _f_zoomStep[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5299660647364774451UL, 18377850681699746435UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_yRotation;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_yRotation => _ufle12jhs77_f_yRotation ?? (_ufle12jhs77_f_yRotation = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5533397032132003805UL, 4547067434773137053UL), () => _ufle12jhs77_f_yRotation = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_zoomStep;
	public static BansheeGz.BGDatabase.BGFieldInt _f_zoomStep => _ufle12jhs77_f_zoomStep ?? (_ufle12jhs77_f_zoomStep = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5210402108036421746UL, 7626452185731674296UL), () => _ufle12jhs77_f_zoomStep = null));
	public List<BGEntity> RelatedPlayerListUsingcameraRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_Player._f_camera, Entity.Id);
}
