using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Player = M_Player;
using Alias_rifegrt_Member = M_Member;
using Alias_rifegrt_NPC = M_NPC;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Character")]
public partial class M_Character : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5695581996915272717UL,11651780382815789707UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public BansheeGz.BGDatabase.BGEntity f_scene
	{
		get => _f_scene[Entity.Index];
		set => _f_scene[Entity.Index] = value;
	}
	public UnityEngine.Vector3 f_position
	{
		get => _f_position[Entity.Index];
		set => _f_position[Entity.Index] = value;
	}
	public UnityEngine.Sprite f_portrait => _f_portrait[Entity.Index];
	public BansheeGz.BGDatabase.BGEntity f_stats
	{
		get => _f_stats[Entity.Index];
		set => _f_stats[Entity.Index] = value;
	}
	public BansheeGz.BGDatabase.BGEntity f_bags
	{
		get => _f_bags[Entity.Index];
		set => _f_bags[Entity.Index] = value;
	}
	public BansheeGz.BGDatabase.BGEntity f_equipment
	{
		get => _f_equipment[Entity.Index];
		set => _f_equipment[Entity.Index] = value;
	}
	public BansheeGz.BGDatabase.BGEntity f_actionBar
	{
		get => _f_actionBar[Entity.Index];
		set => _f_actionBar[Entity.Index] = value;
	}
	public UnityEngine.GameObject f_prefab => _f_prefab[Entity.Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5066101213488819417UL, 17064203087611126677UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_scene;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_scene => _ufle12jhs77_f_scene ?? (_ufle12jhs77_f_scene = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5540037261082760042UL, 268341880900567682UL), () => _ufle12jhs77_f_scene = null));
	private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_f_position;
	public static BansheeGz.BGDatabase.BGFieldVector3 _f_position => _ufle12jhs77_f_position ?? (_ufle12jhs77_f_position = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldVector3>(MetaDefault, new BGId(5182753954474204576UL, 10230507792308613761UL), () => _ufle12jhs77_f_position = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_f_portrait;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _f_portrait => _ufle12jhs77_f_portrait ?? (_ufle12jhs77_f_portrait = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5396659168586361506UL, 4638749789869639835UL), () => _ufle12jhs77_f_portrait = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_stats;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_stats => _ufle12jhs77_f_stats ?? (_ufle12jhs77_f_stats = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5149010344319408123UL, 8589558891186712965UL), () => _ufle12jhs77_f_stats = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_bags;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_bags => _ufle12jhs77_f_bags ?? (_ufle12jhs77_f_bags = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5426858808760316558UL, 15709710898746427066UL), () => _ufle12jhs77_f_bags = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_equipment;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_equipment => _ufle12jhs77_f_equipment ?? (_ufle12jhs77_f_equipment = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5664870419656475136UL, 13852156309336467335UL), () => _ufle12jhs77_f_equipment = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_actionBar;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_actionBar => _ufle12jhs77_f_actionBar ?? (_ufle12jhs77_f_actionBar = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5442727740881851997UL, 14130639031466187194UL), () => _ufle12jhs77_f_actionBar = null));
	private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_f_prefab;
	public static BansheeGz.BGDatabase.BGFieldUnityPrefab _f_prefab => _ufle12jhs77_f_prefab ?? (_ufle12jhs77_f_prefab = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(MetaDefault, new BGId(5527922004271875830UL, 14062602144096245143UL), () => _ufle12jhs77_f_prefab = null));
	public List<BGEntity> RelatedPlayerListUsingownCharacterRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_Player._f_ownCharacter, Entity.Id);
	public List<BGEntity> RelatedMemberListUsingmemberRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_Member._f_member, Entity.Id);
	public List<BGEntity> RelatedNPCListUsingnpcRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_NPC._f_npc, Entity.Id);
}
