using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_InventorySlot = M_InventorySlot;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Consumable")]
public partial class M_Consumable : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4916262565051699121UL,8244812469903092653UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public System.Int32 f_ConsumeAmount => _f_ConsumeAmount[Entity.Index];
	public UnityEngine.Sprite f_Icon => _f_Icon[Entity.Index];
	public System.String f_Description => _f_Description[Entity.Index];
	public System.Int32 f_Cost => _f_Cost[Entity.Index];
	public System.Int32 f_MaxStackSize => _f_MaxStackSize[Entity.Index];
	public System.String f_Type => _f_Type[Entity.Index];
	public System.String f_onExecute
	{
		get => _f_onExecute[Entity.Index];
		set => _f_onExecute[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5146900854736722741UL, 1646468645119950723UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_ConsumeAmount;
	public static BansheeGz.BGDatabase.BGFieldInt _f_ConsumeAmount => _ufle12jhs77_f_ConsumeAmount ?? (_ufle12jhs77_f_ConsumeAmount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5196428320316050209UL, 8158881751340513693UL), () => _ufle12jhs77_f_ConsumeAmount = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_f_Icon;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _f_Icon => _ufle12jhs77_f_Icon ?? (_ufle12jhs77_f_Icon = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(4963497235268065391UL, 15891794619153138574UL), () => _ufle12jhs77_f_Icon = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Description;
	public static BansheeGz.BGDatabase.BGFieldString _f_Description => _ufle12jhs77_f_Description ?? (_ufle12jhs77_f_Description = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4785627298522520254UL, 8221708878267110280UL), () => _ufle12jhs77_f_Description = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Cost;
	public static BansheeGz.BGDatabase.BGFieldInt _f_Cost => _ufle12jhs77_f_Cost ?? (_ufle12jhs77_f_Cost = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5538698272955041288UL, 14223728054253298351UL), () => _ufle12jhs77_f_Cost = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_MaxStackSize;
	public static BansheeGz.BGDatabase.BGFieldInt _f_MaxStackSize => _ufle12jhs77_f_MaxStackSize ?? (_ufle12jhs77_f_MaxStackSize = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5283523825771409457UL, 15350556750792633476UL), () => _ufle12jhs77_f_MaxStackSize = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Type;
	public static BansheeGz.BGDatabase.BGFieldString _f_Type => _ufle12jhs77_f_Type ?? (_ufle12jhs77_f_Type = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5008717157317803801UL, 2123623589406567610UL), () => _ufle12jhs77_f_Type = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_onExecute;
	public static BansheeGz.BGDatabase.BGFieldString _f_onExecute => _ufle12jhs77_f_onExecute ?? (_ufle12jhs77_f_onExecute = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5166315398823752159UL, 13194928096265363609UL), () => _ufle12jhs77_f_onExecute = null));
	public List<BGEntity> RelatedInventorySlotListUsingItemRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_InventorySlot._f_Item, Entity.Id);
}
