using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_EquipmentInvLoadout")]
public partial class M_EquipmentInvLoadout : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5302842945222210657UL,6683220441940177553UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public System.Int32 f_numberProfiles
	{
		get => _f_numberProfiles[Entity.Index];
		set => _f_numberProfiles[Entity.Index] = value;
	}
	public BansheeGz.BGDatabase.BGEntity f_Profile
	{
		get => _f_Profile[Entity.Index];
		set => _f_Profile[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5456023620051893500UL, 10951443102205077635UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_numberProfiles;
	public static BansheeGz.BGDatabase.BGFieldInt _f_numberProfiles => _ufle12jhs77_f_numberProfiles ?? (_ufle12jhs77_f_numberProfiles = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4928839988653452509UL, 9146388542140470940UL), () => _ufle12jhs77_f_numberProfiles = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_Profile;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Profile => _ufle12jhs77_f_Profile ?? (_ufle12jhs77_f_Profile = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5539927277232400804UL, 1086356859864766629UL), () => _ufle12jhs77_f_Profile = null));
}
