using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_EquipmentInventory = M_EquipmentInventory;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_EquipmentSlot")]
public partial class M_EquipmentSlot : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4711005513373031845UL,12969416796084967302UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public RPGCore.Item.EquipmentTypes f_ValidSlotType
	{
		get => (RPGCore.Item.EquipmentTypes) _f_ValidSlotType.GetStoredValue(Entity.Index);
		set => _f_ValidSlotType.SetStoredValue(Entity.Index, (System.Int32) value);
	}
	public BansheeGz.BGDatabase.BGEntity f_slot
	{
		get => _f_slot[Entity.Index];
		set => _f_slot[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5404284805870651722UL, 9612575412410576554UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_f_ValidSlotType;
	public static BansheeGz.BGDatabase.BGFieldEnum _f_ValidSlotType => _ufle12jhs77_f_ValidSlotType ?? (_ufle12jhs77_f_ValidSlotType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(5152285422122985041UL, 6994705325713516199UL), () => _ufle12jhs77_f_ValidSlotType = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_slot;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_slot => _ufle12jhs77_f_slot ?? (_ufle12jhs77_f_slot = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5577353756343372351UL, 14987841716306405551UL), () => _ufle12jhs77_f_slot = null));
	public List<BGEntity> RelatedEquipmentInventoryListUsingslotsRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_EquipmentInventory._f_slots, Entity.Id);
}
