using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_EquipmentInvDefinition")]
public partial class M_EquipmentInvDefinition : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4707756288605260978UL,14481916412973536663UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public RPGCore.Item.EquipmentTypes f_ValidSlotType
	{
		get => (RPGCore.Item.EquipmentTypes) _f_ValidSlotType.GetStoredValue(Entity.Index);
		set => _f_ValidSlotType.SetStoredValue(Entity.Index, (System.Int32) value);
	}
	public System.Int32 f_LoadoutProfile
	{
		get => _f_LoadoutProfile[Entity.Index];
		set => _f_LoadoutProfile[Entity.Index] = value;
	}
	public System.String f_LoadoutName
	{
		get => _f_LoadoutName[Entity.Index];
		set => _f_LoadoutName[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4734643831536598444UL, 3493311124039207339UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_f_ValidSlotType;
	public static BansheeGz.BGDatabase.BGFieldEnum _f_ValidSlotType => _ufle12jhs77_f_ValidSlotType ?? (_ufle12jhs77_f_ValidSlotType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(5760176142694839192UL, 12764152060516414369UL), () => _ufle12jhs77_f_ValidSlotType = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_LoadoutProfile;
	public static BansheeGz.BGDatabase.BGFieldInt _f_LoadoutProfile => _ufle12jhs77_f_LoadoutProfile ?? (_ufle12jhs77_f_LoadoutProfile = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4784089088431595332UL, 2610725894272027809UL), () => _ufle12jhs77_f_LoadoutProfile = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_LoadoutName;
	public static BansheeGz.BGDatabase.BGFieldString _f_LoadoutName => _ufle12jhs77_f_LoadoutName ?? (_ufle12jhs77_f_LoadoutName = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5116230510373440338UL, 11713863919640322711UL), () => _ufle12jhs77_f_LoadoutName = null));
}
