using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_EquipmentInvLoadout = M_EquipmentInvLoadout;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_EquipmentInvProfile")]
public partial class M_EquipmentInvProfile : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5441339525291847066UL,18224336839527134129UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public List<RPGCore.Item.EquipmentTypes> f_ProfileSlots
	{
		get => BGCodeGenUtils.EnumListGet<RPGCore.Item.EquipmentTypes>(_f_ProfileSlots, Entity.Index);
		set => BGCodeGenUtils.EnumListSet<RPGCore.Item.EquipmentTypes>(_f_ProfileSlots, Entity.Index, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5452844216356116701UL, 13062009509601832586UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldEnumList _ufle12jhs77_f_ProfileSlots;
	public static BansheeGz.BGDatabase.BGFieldEnumList _f_ProfileSlots => _ufle12jhs77_f_ProfileSlots ?? (_ufle12jhs77_f_ProfileSlots = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnumList>(MetaDefault, new BGId(5158509927602457545UL, 12660071665909260188UL), () => _ufle12jhs77_f_ProfileSlots = null));
	public List<BGEntity> RelatedEquipmentInvLoadoutListUsingProfileRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_EquipmentInvLoadout._f_Profile, Entity.Id);
}
