using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_InventorySlot = M_InventorySlot;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Item")]
public partial class M_Item : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5414818254486887947UL,7669228068788112030UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public UnityEngine.Sprite f_Icon => _f_Icon[Entity.Index];
	public System.String f_Description => _f_Description[Entity.Index];
	public System.Int32 f_Cost => _f_Cost[Entity.Index];
	public System.Int32 f_MaxStackSize => _f_MaxStackSize[Entity.Index];
	public System.String f_Type => _f_Type[Entity.Index];
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5340576956682203118UL, 4478266436427473550UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_f_Icon;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite _f_Icon => _ufle12jhs77_f_Icon ?? (_ufle12jhs77_f_Icon = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5537744282261313149UL, 12230921913758717591UL), () => _ufle12jhs77_f_Icon = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Description;
	public static BansheeGz.BGDatabase.BGFieldString _f_Description => _ufle12jhs77_f_Description ?? (_ufle12jhs77_f_Description = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4924280058490476706UL, 8108328657455946671UL), () => _ufle12jhs77_f_Description = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Cost;
	public static BansheeGz.BGDatabase.BGFieldInt _f_Cost => _ufle12jhs77_f_Cost ?? (_ufle12jhs77_f_Cost = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5599295672549531882UL, 3280060961465323192UL), () => _ufle12jhs77_f_Cost = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_MaxStackSize;
	public static BansheeGz.BGDatabase.BGFieldInt _f_MaxStackSize => _ufle12jhs77_f_MaxStackSize ?? (_ufle12jhs77_f_MaxStackSize = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5389507791964770159UL, 9032145622332022403UL), () => _ufle12jhs77_f_MaxStackSize = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Type;
	public static BansheeGz.BGDatabase.BGFieldString _f_Type => _ufle12jhs77_f_Type ?? (_ufle12jhs77_f_Type = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5444274582154713088UL, 16119110015688631958UL), () => _ufle12jhs77_f_Type = null));
	public List<BGEntity> RelatedInventorySlotListUsingItemRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_InventorySlot._f_Item, Entity.Id);
}
