using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Member")]
public partial class M_Member : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5597563292818494664UL,16433317915391479740UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public BansheeGz.BGDatabase.BGEntity f_party
	{
		get => _f_party[Entity.Index];
		set => _f_party[Entity.Index] = value;
	}
	public BansheeGz.BGDatabase.BGEntity f_member
	{
		get => _f_member[Entity.Index];
		set => _f_member[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5587953385998744849UL, 17367257419699956652UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_party;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_party => _ufle12jhs77_f_party ?? (_ufle12jhs77_f_party = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5258007073494105878UL, 3658520038331914925UL), () => _ufle12jhs77_f_party = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_member;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_member => _ufle12jhs77_f_member ?? (_ufle12jhs77_f_member = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5715812396495931444UL, 11745860963159889849UL), () => _ufle12jhs77_f_member = null));
}
