using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Party")]
public partial class M_Party : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5236616946484876263UL,11332414068773521552UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public UnityEngine.GameObject f_prefab => _f_prefab[Entity.Index];
	public UnityEngine.GameObject f_partyMemberPrefab => _f_partyMemberPrefab[Entity.Index];
	public System.Collections.Generic.List<BansheeGz.BGDatabase.BGEntity> f_Member => _f_Member[Entity.Index];
	public BansheeGz.BGDatabase.BGEntity f_Stash
	{
		get => _f_Stash[Entity.Index];
		set => _f_Stash[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4731986484936909513UL, 9008785436474953859UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_f_prefab;
	public static BansheeGz.BGDatabase.BGFieldUnityPrefab _f_prefab => _ufle12jhs77_f_prefab ?? (_ufle12jhs77_f_prefab = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(MetaDefault, new BGId(5446797486091105079UL, 13591658418135441827UL), () => _ufle12jhs77_f_prefab = null));
	private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_f_partyMemberPrefab;
	public static BansheeGz.BGDatabase.BGFieldUnityPrefab _f_partyMemberPrefab => _ufle12jhs77_f_partyMemberPrefab ?? (_ufle12jhs77_f_partyMemberPrefab = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(MetaDefault, new BGId(4714848102527597748UL, 1962429984229904546UL), () => _ufle12jhs77_f_partyMemberPrefab = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_Member;
	public static BansheeGz.BGDatabase.BGFieldNested _f_Member => _ufle12jhs77_f_Member ?? (_ufle12jhs77_f_Member = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(4978753513316310517UL, 10540910825046158UL), () => _ufle12jhs77_f_Member = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_Stash;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Stash => _ufle12jhs77_f_Stash ?? (_ufle12jhs77_f_Stash = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4973812207885906641UL, 17152185456407138688UL), () => _ufle12jhs77_f_Stash = null));
}
