using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Slot")]
public partial class M_Slot : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5282350431612775190UL,16830709627832361877UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name => _f_name[Entity.Index];
	public BansheeGz.BGDatabase.BGEntity f_Inventory
	{
		get => _f_Inventory[Entity.Index];
		set => _f_Inventory[Entity.Index] = value;
	}
	public BansheeGz.BGDatabase.BGEntity f_item
	{
		get => _f_item[Entity.Index];
		set => _f_item[Entity.Index] = value;
	}
	public System.Int32 f_stacks
	{
		get => _f_stacks[Entity.Index];
		set => _f_stacks[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4975011018137269444UL, 17219779172153459386UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_Inventory;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Inventory => _ufle12jhs77_f_Inventory ?? (_ufle12jhs77_f_Inventory = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5218105242561751649UL, 4271017023653494414UL), () => _ufle12jhs77_f_Inventory = null));
	private static BansheeGz.BGDatabase.BGFieldViewRelationSingle _ufle12jhs77_f_item;
	public static BansheeGz.BGDatabase.BGFieldViewRelationSingle _f_item => _ufle12jhs77_f_item ?? (_ufle12jhs77_f_item = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldViewRelationSingle>(MetaDefault, new BGId(4961363947729263506UL, 9336084377900531368UL), () => _ufle12jhs77_f_item = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_stacks;
	public static BansheeGz.BGDatabase.BGFieldInt _f_stacks => _ufle12jhs77_f_stacks ?? (_ufle12jhs77_f_stacks = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5732724002254829533UL, 8659857761384040116UL), () => _ufle12jhs77_f_stacks = null));
}
