using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Character = M_Character;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_StatBlock")]
public partial class M_StatBlock : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5474654791986622203UL,12065216000745993396UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public System.Collections.Generic.List<BansheeGz.BGDatabase.BGEntity> f_stats
	{
		get => _f_stats[Entity.Index];
		set => _f_stats[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4904061257593934277UL, 15643566533458838709UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldViewRelationMultiple _ufle12jhs77_f_stats;
	public static BansheeGz.BGDatabase.BGFieldViewRelationMultiple _f_stats => _ufle12jhs77_f_stats ?? (_ufle12jhs77_f_stats = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldViewRelationMultiple>(MetaDefault, new BGId(5239685835416637368UL, 6986247686252584106UL), () => _ufle12jhs77_f_stats = null));
	public List<BGEntity> RelatedCharacterListUsingstatsRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_Character._f_stats, Entity.Id);
}
