using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_StatBlock = M_StatBlock;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Vital")]
public partial class M_Vital : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4865268051403872308UL,13740500449276124057UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public BansheeGz.BGDatabase.BGEntity f_definition
	{
		get => _f_definition[Entity.Index];
		set => _f_definition[Entity.Index] = value;
	}
	public System.Single f_currentValue
	{
		get => _f_currentValue[Entity.Index];
		set => _f_currentValue[Entity.Index] = value;
	}
	public System.Single f_baseValue
	{
		get => _f_baseValue[Entity.Index];
		set => _f_baseValue[Entity.Index] = value;
	}
	public System.String f_type
	{
		get => _f_type[Entity.Index];
		set => _f_type[Entity.Index] = value;
	}
	public System.Single f_value
	{
		get => _f_value[Entity.Index];
		set => _f_value[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5061856827431088755UL, 11303878245003970184UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_definition;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_definition => _ufle12jhs77_f_definition ?? (_ufle12jhs77_f_definition = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4851276027630903990UL, 15030972980522014634UL), () => _ufle12jhs77_f_definition = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_currentValue;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_currentValue => _ufle12jhs77_f_currentValue ?? (_ufle12jhs77_f_currentValue = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4813127768532943214UL, 4409370320376540333UL), () => _ufle12jhs77_f_currentValue = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_baseValue;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_baseValue => _ufle12jhs77_f_baseValue ?? (_ufle12jhs77_f_baseValue = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4783253466091537150UL, 16869509063905930162UL), () => _ufle12jhs77_f_baseValue = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_type;
	public static BansheeGz.BGDatabase.BGFieldString _f_type => _ufle12jhs77_f_type ?? (_ufle12jhs77_f_type = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4652682848943615789UL, 12113186235544523674UL), () => _ufle12jhs77_f_type = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_f_value;
	public static BansheeGz.BGDatabase.BGFieldFloat _f_value => _ufle12jhs77_f_value ?? (_ufle12jhs77_f_value = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5315075500724312339UL, 1853616761041761710UL), () => _ufle12jhs77_f_value = null));
	public List<BGEntity> RelatedStatBlockListUsingstatsRelation => BGCodeGenUtils.GetRelatedInbound<BansheeGz.BGDatabase.BGEntity>(Alias_rifegrt_StatBlock._f_stats, Entity.Id);
}
